/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import componentBean.DBConnection;
import componentBean.SessionParameter;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.xml.bind.JAXBException;
import xmlBean.Reference;

/**
 *
 * @author nimeshd
 */
public class ManageConnection extends javax.swing.JFrame {

    /**
     * Creates new form ManageConnection
     */
    public ManageConnection() {
        somethingChanged = false;
        this.defaultBorder = new LineBorder(Color.LIGHT_GRAY);
        dbConnNames = new XMLHelper.ConnectionHelper().getDBConnectionNames();
        if (dbConnNames != null) {
            for (String s : dbConnNames) {
                this.defautListModel.addElement(s);
            }
        }
        /*
        jList1.addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
        String selectedConnName = jList1.getSelectedValue();
        try {
        Reference connRef = new XMLHelper.ConnectionHelper().getDBReference(selectedConnName);
        DBConnection connDetails = new XMLHelper.ConnectionHelper().extractDBConnection(connRef);
        jTextField3.setText(connDetails.getConnectionName());
        jTextField2.setText(connDetails.getUsername());
        jTextField5.setText(connDetails.getHost());
        jTextField6.setText(String.valueOf(connDetails.getPort()));
        if(connDetails.getServiceID()!=null)    jTextField8.setText(selectedConnName);
        if(connDetails.getServiceName()!=null)  jTextField7.setText(selectedConnName);
        jPasswordField1.setText(connDetails.getPassword());
        } catch (JAXBException ex) {
        Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        });*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Data Source");
        setLocation(new java.awt.Point(300, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jList1.setModel(defautListModel);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField1.setToolTipText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel1.setText("Connection Name");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DB Server"));

        jLabel4.setText("Hostname");

        jLabel5.setText("Port");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("SID");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("SName");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField5.setName("password"); // NOI18N

        jTextField6.setName("password"); // NOI18N

        jTextField7.setEnabled(false);
        jTextField7.setName("password"); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setName(""); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel6.setText("Status");

        jLabel7.setText(":");
        jLabel7.setName("statusLabel"); // NOI18N
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jLabel7.getAccessibleContext().setAccessibleName("statusLabel");

        jTextField2.setName("username"); // NOI18N

        jTextField3.setName("connectionName"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Close");
        jButton3.setName("cancelButton"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Test");
        jButton4.setName("testButton"); // NOI18N
        jButton4.setSelected(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Save as New");
        jButton5.setName("saveButton"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");
        jButton6.setName("resetButton"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jLabel7.setForeground(Color.BLACK);
        jLabel7.setText("");
        jTextField1.setText(null);
        jTextField1.setBorder(defaultBorder);
        jTextField2.setText(null);
        jTextField2.setBorder(defaultBorder);
        jTextField3.setText(null);
        jTextField3.setBorder(defaultBorder);
        jPasswordField1.setText(null);
        jPasswordField1.setBorder(defaultBorder);
        jTextField5.setText(null);
        jTextField5.setBorder(defaultBorder);
        jTextField6.setText(null);
        jTextField6.setBorder(defaultBorder);
        jTextField7.setText(null);
        jTextField7.setBorder(defaultBorder);
        jTextField8.setText(null);
        jTextField8.setBorder(defaultBorder);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel7.setForeground(Color.BLACK);
        jLabel7.setText("");
        if (!checkEmptyFields()) {
            prepareDBConnectionFromInput();
            try {
                if (new XMLHelper.ConnectionHelper().testDBConnection(connectionDetails)) {
                    jLabel7.setText("Success");
                    jLabel7.setForeground(Color.BLACK);
                    connectionDetails.setCustURL(null);
                } else {
                    jLabel7.setText("Failed to connect");
                    jLabel7.setForeground(Color.RED);
                    connectionDetails.setCustURL(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Cannot Proceed with full DB details");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void prepareDBConnectionFromInput() {
        connectionDetails.setConnectionName(jTextField3.getText());
        connectionDetails.setUsername(jTextField2.getText());
        connectionDetails.setPassword(String.valueOf(jPasswordField1.getPassword()));
        connectionDetails.setHost(jTextField5.getText());
        connectionDetails.setPort(Integer.parseInt(jTextField6.getText()));
        if (jRadioButton1.isSelected()) {
            connectionDetails.setServiceID(jTextField8.getText());
        }
        if (jRadioButton2.isSelected()) {
            connectionDetails.setServiceName(jTextField7.getText());
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel7.setForeground(Color.BLACK);
        jLabel7.setText("");
        if (!checkEmptyFields()) {
            prepareDBConnectionFromInput();
            try {
                if (!new XMLHelper.ConnectionHelper().testDBConnection(connectionDetails)) {
                    jLabel7.setText("Failed to connect");
                    jLabel7.setForeground(Color.RED);
                    connectionDetails.setCustURL(null);
                } else {
                    if (new XMLHelper.ConnectionHelper().saveDBConnection(connectionDetails)) {
                        defautListModel.addElement(connectionDetails.getConnectionName());
                        JOptionPane.showMessageDialog(null, "DB details saved successfully");
                        System.out.println("Connections have been modified");
                        this.setVisible(false);
                        new ManageConnection().setVisible(true);
                        somethingChanged = true;
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        nowDispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            jTextField8.setEnabled(true);
            jTextField7.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()) {
            jTextField8.setEnabled(false);
            jTextField7.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        String key = jTextField1.getText().toLowerCase();
        DefaultListModel<String> model = new DefaultListModel<>();
        jList1.setModel(defautListModel);
        if (key != null) {
            if (dbConnNames != null) {
                for (String s : dbConnNames) {
                    if (s.toLowerCase().startsWith(key)) {
                        model.addElement(s);
                    }
                }
                if (model.size() == 0) {
                    model.addElement("No DB Found");
                }
            } else {
                model.addElement("No DB Found");
            }
            jList1.setModel(model);
        } else {
            jList1.setModel(defautListModel);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        jLabel7.setText(":");
        String selectedConnName = jList1.getSelectedValue();
        try {
            Reference connRef = new XMLHelper.ConnectionHelper().getDBReference(selectedConnName);
            DBConnection connDetails = new XMLHelper.ConnectionHelper().extractDBConnection(connRef);
            jTextField3.setText(connDetails.getConnectionName());
            jTextField2.setText(connDetails.getUsername());
            jTextField5.setText(connDetails.getHost());
            jTextField6.setText(String.valueOf(connDetails.getPort()));
            if (connDetails.getServiceID() != null) {
                jRadioButton1.setSelected(true);
                jTextField8.setText(connDetails.getServiceID());
                jTextField8.setEnabled(true);
                jTextField7.setText(null);
                jTextField7.setEnabled(false);
            }
            if (connDetails.getServiceName() != null) {
                jRadioButton2.setSelected(true);
                jTextField7.setText(connDetails.getServiceName());
                jTextField7.setEnabled(true);
                jTextField8.setText(null);
                jTextField8.setEnabled(false);
            }
            jPasswordField1.setText(connDetails.getPassword());
        } catch (JAXBException ex) {
            Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel7.setForeground(Color.BLACK);
        jLabel7.setText("");
        List<String> selectedValuesList = jList1.getSelectedValuesList();
        List<String> errorConn = new ArrayList<>(selectedValuesList);
        int initialSize = errorConn.size();
        if (selectedValuesList.size() > 0) {
            for (String s : selectedValuesList) {
                try {
                    Reference connRef = new XMLHelper.ConnectionHelper().getDBReference(s);
                    if (connRef != null) {
                        if (new XMLHelper.ConnectionHelper().deleteDBConnection(s)) {
                            somethingChanged = true;
                            System.out.println("Deleted " + s);
                            errorConn.remove(s);
                        }
                    } else {
                        System.out.println("Connection Reference found null, cannot delete " + s);
                    }
                } catch (JAXBException ex) {
                    Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (errorConn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Successfully deleted connections: " + errorConn.toString().replace("[", "").replace("]", ""));
        } else {
            JOptionPane.showMessageDialog(null, "Cannot delete connections: " + errorConn.toString().replace("[", "").replace("]", ""));
        }
        dispose();
        new ManageConnection().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel7.setForeground(Color.BLACK);
        jLabel7.setText("");
        if (!checkEmptyFields()) {
            prepareDBConnectionFromInput();
            try {
                if (!new XMLHelper.ConnectionHelper().testDBConnection(connectionDetails)) {
                    jLabel7.setText("Failed to connect");
                    jLabel7.setForeground(Color.RED);
                    connectionDetails.setCustURL(null);
                } else {
                    if (new XMLHelper.ConnectionHelper().modifyDBConnection(connectionDetails)) {
                        defautListModel.addElement(connectionDetails.getConnectionName());
                        JOptionPane.showMessageDialog(null, "DB details saved successfully");
                        System.out.println("Connections have been modified");
                        somethingChanged = true;
                        this.setVisible(false);
                        new ManageConnection().setVisible(true);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageConnection.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        nowDispose();
    }//GEN-LAST:event_formWindowClosing

    private boolean checkEmptyFields() {
        int i = 0;
        Border LineBorder = new LineBorder(Color.RED);
        if (jTextField3.getText().isEmpty() || jTextField3.getText() == null) {
            jTextField3.setBorder(LineBorder);
            i = 1;
        }
        if (!jTextField3.getText().isEmpty()) {
            jTextField3.setBorder(defaultBorder);
        }

        if (jTextField2.getText().isEmpty() || jTextField2.getText() == null) {
            jTextField2.setBorder(LineBorder);
            i = 2;
        }
        if (!jTextField2.getText().isEmpty()) {
            jTextField2.setBorder(defaultBorder);
        }

        if (String.valueOf(jPasswordField1.getPassword()).isEmpty() || String.valueOf(jPasswordField1.getPassword()) == null) {
            jPasswordField1.setBorder(LineBorder);
            i = 3;
        }
        if (!String.valueOf(jPasswordField1.getPassword()).isEmpty()) {
            jPasswordField1.setBorder(defaultBorder);
        }

        if (jTextField5.getText().isEmpty() || jTextField5.getText() == null) {
            jTextField5.setBorder(LineBorder);
            i = 4;
        }
        if (!jTextField5.getText().isEmpty()) {
            jTextField5.setBorder(defaultBorder);
        }

        if (jTextField6.getText().isEmpty() || jTextField6.getText() == null) {
            jTextField6.setBorder(LineBorder);
            i = 5;
        }
        if (!jTextField6.getText().isEmpty()) {
            jTextField6.setBorder(defaultBorder);
        }

        if (jRadioButton1.isSelected() && (jTextField8.getText().isEmpty() || jTextField8.getText() == null)) {
            jTextField8.setBorder(LineBorder);
            i = 6;
        }
        if (jRadioButton1.isSelected() && !jTextField8.getText().isEmpty()) {
            jTextField8.setBorder(defaultBorder);
        }

        if (jRadioButton2.isSelected() && (jTextField7.getText().isEmpty() || jTextField7.getText() == null)) {
            jTextField7.setBorder(LineBorder);
            i = 7;
        }
        if (jRadioButton2.isSelected() && !jTextField7.getText().isEmpty()) {
            jTextField7.setBorder(defaultBorder);
        }
        return i > 0;
    }

    /**
     */
    public static void manageConnectionMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageConnection().setVisible(true);
            }
        });
    }

    /*
    public static void main(String[] args) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageConnection().setVisible(true);
            }
        });
    }*/
    private final Border defaultBorder;
    private DefaultListModel<String> defautListModel = new DefaultListModel<>();
    private DBConnection connectionDetails = new DBConnection();
    public String[] dbConnNames;
    public static boolean somethingChanged;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void nowDispose() {
        dispose();
        List<SessionParameter> list = new ArrayList<>();
        SessionParameter sp = new SessionParameter();
        /*if(somethingChanged){
            System.out.println("Inside something modified");
            sp.setParamName("Response");
            sp.setParamValue("true");
            list.add(sp);
        }*/
        int count = 0;
        for (Frame f : Frame.getFrames()) {
            if (f.getClass().getName().equals("gui.HomePage")) {
                count++;
                if (count == 1) {
                    new HomePage().mainHome(null);
                }
                f.dispose();
            }
        }
    }
}
